#include "QuestUI/shared/BeatSaberUI.hpp"
using namespace QuestUI;

#include "UI/ModUI.hpp"
using namespace AIMod::UI;
DEFINE_TYPE(AIMod::UI, AIModUI);

void AIModUI::DidActivate(bool firstActivation) 
{
    if (firstActivation) {
        auto scrollView = BeatSaberUI::CreateScrollView(get_transform());
        BeatSaberUI::CreateText(scrollView, "Generated by AI!");
    }
}


// Written by AI